const SEASONS = {
    "8": {
        name: "🎸 8 СЕЗОН",
        folder: "8_season",
        dev: false,
        songs: [
            { name: "Про друзей", file: "Про друзей.mp3" },
            { name: "Не переживай", file: "Не переживай.mp3" },
            { name: "База", file: "База.mp3" },
            { name: "Море", file: "Море.mp3" },
            { name: "Алые пожары", file: "Алые пожары.mp3" },
            { name: "Романс", file: "Романс.mp3" },
            { name: "Она любовь", file: "Она любовь.mp3" },
            { name: "Последнее лето", file: "Последнее лето (Demo Version).mp3" },
            { name: "Lullaby for the Weary", file: "Lullaby for the Weary.m4a" },
            { name: "Прогулка с собакой", file: "Прогулка с собакой.mp3" },
            { name: "Ни с одной", file: "Ни с одной.mp3" },
            { name: "SHRAMY", file: "SHRAMY.mp3" },
            { name: "Тени от пальм", file: "Тени от пальм.mp3" },
            { name: "Не я", file: "Не я.mp3" },
            { name: "Нуар", file: "Нуар.mp3" },
            { name: "Лампочки", file: "Лампочки.mp3" },
            { name: "Моя душа", file: "Моя душа.mp3" },
            { name: "Молодая красивая дрянь", file: "молодая красивая дрянь.mp3" },
            { name: "Я уёбываю в джаз", file: "Я уёбываю в джаз.mp3" },
            { name: "Полудница - Гадкий утёнок", file: "Полудница - Гадкий утёнок.mp3" },
            { name: "УГАДАЙКТО - Suck My Balls", file: "УГАДАЙКТО - Suck My Balls.mp3" },
            { name: "Юлия Новоселова", file: "Юлия Новоселова.mp3" },
            { name: "Праздник", file: "Праздник.mp3" },
            { name: "SAWCE", file: "SAWCE.mp3" },
            { name: "Школа не нужна", file: "Школа не нужна.mp3" },
            { name: "Зачемгород", file: "Зачемгород.mp3" }
        ]
    },
    "7": {
        name: "🥁 7 СЕЗОН",
        folder: "7_season",
        dev: false,
        songs: [
            { name: "Only time", file: "Only time.mp3" },
            { name: "Cyberpunkz", file: "Cyberpunkz.mp3" },
            { name: "Shouldve Been Me", file: "Shouldve Been Me.mp3" },
            { name: "Axilla", file: "Axilla.mp3" },
            { name: "Amor Nostalgico", file: "Amor Nostalgico.mp3" },
            { name: "Cant Be There", file: "Cant Be There.mp3" },
            { name: "Sweep the Leg", file: "Sweep the Leg.m4a" },
            { name: "AKA, ШГШ - ОДНО И ТОЖЕ", file: "одно и тоже.mp3" },
            { name: "David Celeste - Ad Meliora", file: "David Celeste - Ad Meliora.m4a" },
            { name: "PWR", file: "PWR.mp3" },
            { name: "Poluta", file: "Poluta.mp3" },
            { name: "Shitty train", file: "Shitty train.mp3" },
            { name: "Before Its Gone", file: "Before Its Gone.mp3" },
            { name: "Anyway", file: "Anyway.m4a" },
            { name: "Edgar Hopp", file: "Edgar Hopp.mp3" },
            { name: "Сироткин - дыхание", file: "Сироткин - дыхание.mp3" },
            { name: "Шгш - Множество дорог", file: "Множество дорог.m4a" },
            { name: "Дерзкий - человеку нужен человек", file: "Человеку нужен человек.mp3" },
            { name: "АКА - Ты похож на кота", file: "АКА, ШГШ - ты похож на кота.mp3" },
            { name: "Спать с тобой", file: "Спать с тобой.mp3" },
            { name: "Нам всего 16", file: "Нам всего 16.m4a" },
            { name: "Шгш - преданный класс (7 сезона)", file: "Шгш - преданный класс (7 сезон ).mp3" },
            { name: "АКА, ШГШ - давай, не ссы", file: "Давай, не ссы.mp3" },
            { name: "Дерзкий - правда или действие", file: "Дерзкий - Правда или действие.mp3" },
            { name: "АКА - Мы", file: "АКА - Мы.mp3" },
            { name: "Шгш - Зодиак", file: "Зодиак.mp3" },
            { name: "Дерзкий - Лайтово", file: "Лайтово.mp3" },
            { name: "Милкис - Аирдроп", file: "Аирдроп.mp3" },

{ name: "Шгш - Принц на белом коне", file: "Принц на белом коне.mp3" },
            { name: "Шгш - на люстрі", file: "Шгш - на люстрi.mp3" },
            { name: "Шгш - Хрущевка", file: "Хрущевка.mp3" },
            { name: "Шгш - Маленький принц", file: "маленький принц.mp3" },
            { name: "Шгш - Пустой вокзал", file: "Пустой вокзал.mp3" }
        ]
    },
    "6": {
        name: "🎹 6 СЕЗОН",
        folder: "6_season",
        dev: false,
        songs: [
            { name: "Мужа дома нету", file: "мужа дома нету.m4a" },
            { name: "Peter Sandberg", file: "Peter Sandberg.mp3" },
            { name: "Jakob ahlbom", file: "Jakob ahlbom.m4a" },
            { name: "SLAMJAKE - BZNS", file: "SLAMJAKE - BZNS.m4a" },
            { name: "Echo Sax End", file: "Echo Sax End.mp3" },
            { name: "Panic Attack", file: "Panic Attack.m4a" },
            { name: "Шгш - Полина", file: "Шгш - Полина.mp3" },
            { name: "Шгш - Цензура", file: "Шгш - Цензура.mp3" },
            { name: "Шгш - Маля", file: "Шгш - Маля.mp3" },
            { name: "Another God", file: "Another God.mp3" },
            { name: "Шгш, Ксюша - на ночевке", file: "Ксюша - на ночевке.mp3" },
            { name: "Candelion_Press", file: "Candelion_Pressure.mp3" },
            { name: "Шгш - ШГШ", file: "Шгш - ШГШ.mp3" },
            { name: "Шгш - Легендарный", file: "Шгш - Легендарный.mp3" },
            { name: "Шгш - Наколки", file: "Шгш - Наколки.mp3" },
            { name: "Шгш - Не переживай", file: "Шгш - Не переживай.mp3" },
            { name: "Шгш - Последняя победа", file: "Шгш - Последняя победа.mp3" },
            { name: "Шгш - Я никогда не буду работать", file: "Шгш - Я никогда не буду работать.mp3" },
            { name: "Шгш - Последняя любовь", file: "шгш последняя любовь .mp3" }
        ]
    },
    "5": {
        name: "🎧 5 СЕЗОН",
        folder: "5_season",
        dev: false,
        songs: [
            { name: "Шгш - Мы рядом", file: "Шгш - Мы рядом.mp3" },
            { name: "Mothers Madness", file: "Mothers Madness.mp3" },
            { name: "Sven Karlsson", file: "Sven Karlsson.mp3" },
            { name: "Def Lev", file: "Def Lev.mp3" },
            { name: "Шгш - я, Дерзкий твой", file: "Шгш - я, дерзкий твой.mp3" },
            { name: "Шгш - школа будет долгой", file: "Шгш - школа будет долгой.mp3" },
            { name: "Шгш - и это прекрасно", file: "Шгш - и это прекрасно.mp3" }
        ]
    },
    "4": {
        name: "📻 4 СЕЗОН",
        folder: "4_season",
        dev: false,
        songs: [
            { name: "Elliot Holmes", file: "Elliot Holmes.mp3" },
            { name: "Дерз, ШГШ - Я дерзкий", file: "Дерз, ШГШ - Я дерзкий.mp3" },
            { name: "Choking Feat Red", file: "Choking Feat Red.m4a" },
            { name: "Shiver Disk - Chase Me", file: "Shiver Disk - Chase Me.m4a" },
            { name: "Confidence Is Key", file: "Confidence Is Key.mp3" },
            { name: "Im a Hurricane", file: "Im a Hurricane.mp3" },
            { name: "Manhattan Mystery", file: "Manhattan.mp3" },
            { name: "Rocket JR", file: "Rocket JR.mp3" },
            { name: "Шгш - Забросили учёбу", file: "Шгш - Забросили учёбу.mp3" },
            { name: "Шгш - преданный класс А сезон", file: "Шгш - преданный класс.mp4" },
            { name: "Шгш - АнжГерКам", file: "Шгш - АнжГерКам.mp3" },
            { name: "Шгш - Последний звонок", file: "Шгш - Последний звонок.mp3" },
            { name: "Шгш - Сколько с тобой", file: "Шгш - Сколько с тобой.mp3" },
            { name: "Шгш - Беда дисс", file: "Шгш - Беда дисс.mp3" },
            { name: "Duke Herrington", file: "Duke Herrington.m4a" },
            { name: "Rockin_For_Decades1", file: "Rockin_For_Decades1.mp3" },
            { name: "Got Something Going", file: "Got Something Going.m4a" },
            { name: "Go Cat Go", file: "Go Cat Go.m4a" },
            { name: "Harry Edvino", file: "Harry Edvino.mp3" },
            { name: "Stickin' Around", file: "Stickin' Around.m4a" },
            { name: "Back to My Roots", file: "Back to My Roots.mp3" },
            { name: "Ludvig Moulim", file: "Ludvig Moulim.m4a" },
            { name: "Peter Crosby", file: "Peter Crosby.m4a" },
            { name: "Purple Guy Song", file: "Purple Guy Song.mp3" },
            { name: "Bring It Back", file: "Bring It Back.m4a" },
            { name: "Strange Roll", file: "Strange Roll.mp3" },
            { name: "Hiding in the Dark", file: "Hiding in the Dark.mp3" },
            { name: "Palace Dinner", file: "Palace Dinner.m4a" },
            { name: "More Than You", file: "More Than You.mp3" },
            { name: "Drunken Sailor", file: "Drunken Sailor.m4a" },
            { name: "Love on a Roll", file: "Love on a Roll.mp3" },
            { name: "max_anson", file: "max_anson.mp3" },
            { name: "Rockin_For_Decades2", file: "Rockin_For_Decades2.mp3" },
            { name: "Mike Franklyn", file: "Mike Franklin.m4a" },
            { name: "Safe Trips", file: "Safe Trips.mp3" },
            { name: "Cleo_Kelley_Wrong_", file: "Cleo_Kelley_Wrong_.mp3" },
            { name: "Left for Dead", file: "Left for Dead.m4a" },
            { name: "Pursuing", file: "Pursuing.mp3" },
            { name: "Roof_Don_t_Care", file: "Roof_Don_t_Care.mp3" },
            { name: "Leave Sadness", file: "Leave Sadness.m4a" },
            { name: "The Whole Nine", file: "The Whole Nine.mp3" },
            { name: "Hiding Out", file: "Hiding Out.m4a" },
            { name: "Magnetic Kid", file: "Magnetic Kid.mp3" },
            { name: "Джаро & Ханза", file: "Джарo & Ханза.m4a" },
            { name: "Red Revision", file: "Red Revision.m4a" },
            { name: "At Stake", file: "At Stake.mp4" },
            { name: "Of Men", file: "Of Men.mp3" },
            { name: "Bottom Of My", file: "Bottom Of My.mp3" },
            { name: "Smartface", file: "Smartface.m4a" },
            { name: "Elijah N", file: "Elijah N.m4a" },
            { name: "8-Bit Hop", file: "8-Bit Hop.mp3" },
            { name: "The Times We", file: "The Times We.mp3" },
            { name: "Rids", file: "Rids.m4a" },
            { name: "Chasing the Truth", file: "Chasing the Truth.mp3" },
            { name: "It Was Newer", file: "It Was Newer.mp3" },
            { name: "I Dare You Dear", file: "I Dare You Dear.mp3" },
            { name: "T. Morri", file: "T. Morri.mp3" },
            { name: "Play It Cool", file: "Play It Cool.mp3" },
            { name: "Epocha", file: "Epocha.mp3" },
            { name: "Tick Tock Boom", file: "Tick Tock Boom.mp3" },
            { name: "Tricks", file: "Tricks.m4a" },
            { name: "Closer to the Light", file: "Closer to the Light.mp3" },
            { name: "_Teya", file: "_Teya.mp3" },
            { name: "The Hardest", file: "The Hardest.m4a" },
            { name: "Skip a Chance", file: "Skip a Chance.m4a" },
            { name: "Coming Through", file: "Coming Through.m4a" },
            { name: "A Shadow on Wigmore", file: "A Shadow on Wigmore.mp4" },
            { name: "My Left Foot", file: "My Left Foot.m4a" },
            { name: "Moorland", file: "Moorland.mp3" }
        ]
    },
    "3": {
        name: "⏳ 3 СЕЗОН",
        folder: "3_season",
        dev: true,
        songs: [{ name: "🚧 В РАЗРАБОТКЕ", file: "" }]
    },
    "2": {
        name: "⏳ 2 СЕЗОН",
        folder: "2_season",
        dev: true,
        songs: [{ name: "🚧 В РАЗРАБОТКЕ", file: "" }]
    },
    "1": {
        name: "⏳ 1 СЕЗОН",
        folder: "1_season",
        dev: true,
        songs: [{ name: "🚧 В РАЗРАБОТКЕ", file: "" }]
    },
    "0": {

name: "🎙️ РЕМИКСЫ",
        folder: "0_season",
        dev: false,
        songs: [
            { name: "Шгш, ремикс - маленький принц", file: "маленький принц.mp3" },
            { name: "Шгш, ремикс - лайтово", file: "Лайтово.mp3" },
            { name: "Шгш, ремикс - последняя любовь", file: "шгш последняя любовь .mp3" },
            { name: "Шгш, ремикс - наколки", file: "Шгш - Наколки.mp3" }
        ]
    },
    "temp": {
        name: "🔄 ВРЕМЕННЫЕ ОРИГИНАЛЫ",
        folder: "temp_originals",
        dev: false,
        temp: true,
        songs: [
            { name: "🔜 Скоро здесь появятся оригиналы песен из серий ШГШ", file: "" },
            { name: "⚡ Следите за обновлениями!", file: "" }
        ]
    }
};